name: Build xcframework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "master"
      - "release/*"

  workflow_dispatch:

jobs:
  build-xcframework:
    runs-on: macos-latest

    steps:
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 4.0.x

      - name: Checkout libchewing
        uses: actions/checkout@v4
        with:
          repository: abaltatech/libchewing
          path: libchewing

      - name: Checkout ios-cmake
        uses: actions/checkout@v4
        with:
          repository: leetal/ios-cmake
          path: ios-cmake

      - name: Setup rust
        shell: bash
        run: |
          rustup target add aarch64-apple-ios
          rustup target add --toolchain stable-aarch64-apple-darwin aarch64-apple-ios-sim
          rustup target add --toolchain stable-aarch64-apple-darwin x86_64-apple-ios

      - name: Build libchewing xcframework
        shell: bash
        working-directory: libchewing/swift
        run: |
          mkdir -p cmake-build && cd cmake-build
          cmake .. -DTOOLCHAIN_FILE=${{ github.workspace }}/ios-cmake/ios.toolchain.cmake
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libchewing.xcframework
          path: libchewing/swift/chewing-simplified/libchewing.xcframework
          if-no-files-found: error

  release:
      needs: build-xcframework
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: libchewing.xcframework
            path: libchewing.xcframework.zip

        - name: Test
          shell: bash
          run: |
           ls -R

        - name: Get version
          shell: bash
          working-directory: swift/chewing-simplified
          id: get_version
          run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

        - name: Update Package.swift
          run: |
            sed -i "s/let version = \".*\"/let version = \"${{ steps.get_version.outputs.VERSION }}\"/" swift/chewing-simplified/Package.swift
            sed -i "s/let checksum = \".*\"/let checksum = \"$(shasum -a 256 libchewing.xcframework.zip | cut -d ' ' -f 1)\"/" swift/chewing-simplified/Package.swift

        - name: Commit and push
          run: |
            git config --local user.email "abalta-github-build@abaltatech.com"
            git config --local user.name "abalta-github-build"
            git add swift/chewing-simplified/Package.swift
            git commit -m "Update Package.swift"
            git status
            git push

        #- name: Release
        #  uses: softprops/action-gh-release@v2
        #  with:
        #   files: libchewing.xcframework.zip
        #   tag_name: ${{ github.ref }}

