name: Build xcframework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "master"
      - "release/*"

  workflow_dispatch:

jobs:
  build-xcframework:
    runs-on: macos-latest

    steps:
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 4.0.x

      - name: Checkout libchewing
        uses: actions/checkout@v4
        with:
          repository: abaltatech/libchewing
          path: libchewing

      - name: Checkout ios-cmake
        uses: actions/checkout@v4
        with:
          repository: leetal/ios-cmake
          path: ios-cmake

      - name: Setup rust
        shell: bash
        run: |
          rustup target add aarch64-apple-ios
          rustup target add --toolchain stable-aarch64-apple-darwin aarch64-apple-ios-sim
          rustup target add --toolchain stable-aarch64-apple-darwin x86_64-apple-ios

      - name: Build libchewing xcframework
        shell: bash
        working-directory: libchewing/swift
        run: |
          mkdir -p cmake-build && cd cmake-build
          cmake .. -DTOOLCHAIN_FILE=${{ github.workspace }}/ios-cmake/ios.toolchain.cmake
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libchewing.xcframework
          path: libchewing/swift/chewing-simplified/libchewing.xcframework
          if-no-files-found: error
